### ISSUE TITLE
Fehlermeldungen beim Auslesen eines JSON Strings

### ISSUE THREAD

**Issue by tschabet** [En3rGy/11087_JSON-Parser#3]
Siehe auch [Beitrag auf KNX User Group](https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/knx-einsteiger/1939500-wechselrichter-json-auslesen)

Beim Auslesen des Json Strings 

{"success":true,"exception":"Query success!","result":{"inverterSN":"XXXXX", "sn":"YYYYY","acpower":3155.0,"yieldtoday":23 .3,"yieldtotal":20203.4,"feedinpower":2677.0,"fee d inenergy":5228.8,"consumeenergy":46232.6,"feedinpo werM2":0.0,"soc":0.0,"peps1":0.0,"peps2":0.0,"peps 3":0.0,"inverterType":"5","inverterStatus":"102 "," uploadTime":"2024-03-02 14:27:06","batPower":0.0,"powerdc1":429.0,"powerdc 2":2864.0,"powerdc3":null,"powerdc4":null,"batS tat us":"2"},"code":0} 

erhalte ich vom Baustein Fehlermeldungen wie "value requested" oder "key not found". Leider komme ich nicht weiter und weiß auch nicht, was ich falsch mache. 

Vielen Dank für einen Tipp!
Schöne Grüße,
Thomas

**Comment by En3rGy** [comment]
Formatiert sieht der JSON-String so aus:
```
{
  "success":true,
  "exception":"Query success!",
  "result": {
    "inverterSN":"XXXXX", 
    "sn":"YYYYY",
    "acpower":3155.0,
    "yieldtoday":23 .3,
    "yieldtotal":20203.4,
    "feedinpower":2677.0,
    "fee d inenergy":5228.8,
    "consumeenergy":46232.6,
    "feedinpo werM2":0.0,
    "soc":0.0,
    "peps1":0.0,
    "peps2":0.0,
    "peps 3":0.0,
    "inverterType":"5",
    "inverterStatus":"102 ",
    "uploadTime":"2024-03-02 14:27:06",
    "batPower":0.0,
    "powerdc1":429.0,
    "powerdc 2":2864.0,
    "powerdc3":null,
    "powerdc4":null,
    "batStatus":"2"
  },
  "code":0
}
```

Soll also z.B. der Wert `batStatus ` ausgewertet werden, muss zuerst `result` abgefragt werden und das Ergebnis dann mit einem neuen Baustein nach `batStatus `.
